thin-edge/tedge-docs

docusaurus.config.js
To allow deploying the website to different domains, it is useful to be able to control the url (domain) and baseUrl via environment variables when building the docusaurus project.
**Example**
The project can be built for different domains (e.g. to host on a fork) by setting the following environment variables, then building the project.
```sh
export DOMAIN=https://reubenmiller.github.io
export BASE_URL=/thin-edge.io/
yarn build
```
The built project files can then be deployed to the matching hosting service.
=> feat: support controlling website configuration during deployment

docusaurus.config.js
Add `edit this page` links on pages shown in the current release to encourage easier edits/contributions from users.
**Example**
=> feat: support 'edit this page' links on the next version only

docusaurus.config.js, src/remark/cmd-run.js, src/remark/meta.js
Convert a code block with the command="<command>" property where the code block contents
replaced with the output of the command.
The plugin will only activate if the code block use the syntax set to `run` and a `command=""` property is set.
**Example**
The following markdown will get converted from:
````
```run title="List items in a directory" command="ls -l" lang="sh"
total 1
-rw-r--r--@   1 tedge  staff     209 Jun 22 11:13 Dockerfile
```
````
to:
````
```sh title="List items in a directory"
total 3
-rw-r--r--@   1 tedge  staff     209 Jun 22 11:13 Dockerfile
-rw-r--r--    1 tedge  staff    2290 Jun 30 22:45 README.md
-rw-r--r--@   1 tedge  staff      89 Jun 22 11:13 babel.config.js
```
````
Where the `command="ls -l"` is executed and the output is used as the code block's contents. …
=> feat: add remark plugin to support running a command to generate code block contents

docusaurus.config.js, package.json, src/remark/mqtt-codeblock.js, src/remark/tedge.js, yarn.lock
Add `te2mqtt` directive to a code block which uses a `tedge mqtt` command which will result in displaying the mqtt information in various formats, e.g. mosquitto_sub/pub cli and generic mqtt info.
**Example**
The following code block in markdown will be converted to tabs by the `te2mqtt` directive. Each tab will show the equivalent command using different cli tools.
````
```sh te2mqtt
tedge mqtt pub tedge/health/tedge-mapper-c8y '{"status":"up","type":"thin-edge.io"}' -q 2 -r
```
````
=> feat: add `te2mqtt` directive to tedge mqtt pub/sub commands as tabs

src/remark/mqtt-codeblock.js, src/remark/tedge.js
Minor improvements to handle more complex command usage.
* Preserve any additional positional arguments (e.g. `tedge mqtt sub '#' > myfile.txt`)
* Only display meta info (retain, qos) if set
* Display `<<emtpy>>` in payload for mqtt tab if payload is empty so it is more obvious for users that it is meant to be empty
=> fix: mqtt code block formatting of complex commands

docusaurus.config.js
By default don't show the error output of the command as a sensible default can be provided.
Ideally the build should fail if a codeblock command is not execute successfully, however it is complicated by the fact that multiple versions are now supported, meaning that there will be two sets of the same binaries (one for the previous version and one for the current version). When this problem is solved (e.g. using custom PATH variables when calling the subproces), then the command can fail noisily.
=> fix: ignore cmdrun errors by default as the user can set a default value to use

docusaurus.config.js, package.json, yarn.lock
Support providing a click-to-zoom option on all images.
The following shows how the images can be imported.
If an image is defined in the markdown you can either provide a link to an image using:
```markdown
```
Or if you want more control of the image (e.g. specifying a default size), then you can use the following snippet in the docs:
```markdown
<p align="center">
<img
src={require('../../images/apama-plugin/apama-project-c8y-software-repository.png').default}
alt="Example banner"
width="40%"
/>
</p>
```
=> feat: support zooming in on images

justfile
A `.version` file will be stored under the versioned docs file.
Below show an example format when using the following manual version from the main branch.
```sh
just checkout-version 0.11.0 main
```
**output file: tedge-docs/versioned_docs/version-0.11.0/.version**
```
0.11.0-186-gc4caa7d43c main
```
=> feat: include mark file when copying versioned info for better traceability

docusaurus.config.js, package.json, yarn.lock
Redirect the older website path to the new root (e.g. without `/html`)
=> feat: support redirect from old website link

docusaurus.config.js, package.json, yarn.lock
This error is only seen in chrome. Other browsers don't seem to be affected.
=> fix(chrome): avoid passive events warnings in console by modifying event handlers

docusaurus.config.js, src/remark/cmd-run.js
Add `logErrors` option to silence the cmd-run plugin warnings when a commands does not execute successfully. Default is disabled for now.
=> feat(cmd-run): add option to silence logging of warnings when a command fails

docusaurus.config.js
Prevent warnings like this in the chrome console:
```
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
```
Fix is discussed [here](https://github.com/orgs/community/discussions/52356).
=> fix(chrome): add permission policy meta data to prevent chrome warnings

src/remark/cmd-run.js
Don't ignore empty code blocks.
For example, the following now works:
````
```run command="ls -l"
```
````
Previously, the above command would not have been executed.
=> fix(cmd-run): execute command even when the code block has no default value

docusaurus.config.js
It moves the Permission-Policy configuration to the `headerTags` section so that the meta tag does not get any additional attributes added to it (which is the case when using the theme config).
It is unconfirmed if this will remove the chrome warning as the warning is only visible when deployed to github pages.
=> fix(chrome): move meta permissions-policy to custom header tag in an attempt to remove the chrome warning

README.md
Update readme and extend the instructions to included checking out versioned docs from a branch instead of a tag.
=> docs: Update readme instructions

docusaurus.config.js, package.json, yarn.lock
Add support for once-off code blocks displayed as a grouped tab.
**Example markdown**
````markdown title="Markdown"
```systemd tab
systemctl status tedge
```
```openrc tab
service tedge status
```
````
**Output**
=> feat: add plugins to display generic code blocks as tabs

src/css/custom.css
Remove unused css related to the previous local search functionality. It is no longer required since moving to using the algolia plugin.
=> chore: remove unused css

docusaurus.config.js
Allowing users to hide (collapse) the sidebar is useful to make the most of available screen realestate.
=> feat: allow the sidebar to be hidden

docusaurus.config.js, src/remark/meta.js, src/remark/mqtt-codeblock.js, src/remark/tedge.js
Support extending the `te2mqtt` Tedge MQTT code block example to display multiple tedge api formats (e.g. `te/` and tedge/` apis).
This is a non-breaking change. The defaults have been set to render the MQTT code block examples exactly how they were done before. Once the new MQTT api is ready, then the features can be activated by default (or slowly opted in per code block).
Support automatically converting the legacy examples to new examples without code changes. This supports a much smoother transition that the docs can be updated to use the new api, and convert back to the old api using a docusaurus configuration option (or vice versa).
The user can control which formats are displayed by either setting the global `formats` array in the `docusaurus.config.js` file, or on individual code …
=> Feat mqtt legacy to new api conversion

versioned_docs/version-0.11.0/references/data-model.md, versioned_docs/version-0.11.0/understand/thin-edge-json.md
The backport is required to avoid any possible conversion errors in the new changes to the mqtt code block features (https://github.com/thin-edge/tedge-docs/pull/36), namely the pretty printing functionality. Invalid json would cause an error in the pretty printing of the mqtt payload.
=> fix(examples): backport the fix to invalid json examples (missing trailing comma)

src/remark/mqtt-codeblock.js
Visualisation improvement to ensure the api version (e.g. legacy or v1) are more prominent to the reader.
Example:
=> feat(te2mqtt): Use strong headers for the different api sections in the generic mqtt tab

docusaurus.config.js
This settings makes urls links more predictable, though it will force users to use the following convention when using url links:
**Correct example**
````markdown
[example](./start/index.md)
````
**Wrong example**
````markdown
[example](./start/)
````
=> chore: normalize trailing slashes on doc links to avoid unnecessary redirects

docusaurus.config.js
This adds a plugin to the dev server to redirect requests to e.g. `/some/page` to `/some/page/`, avoiding surprises from the dev server behaving differently to the production build (e.g. the cause of https://github.com/thin-edge/thin-edge.io/pull/2549).
=> Add plugin to ensure dev server always redirects to trailing slash URLs like the built version

README.md, docusaurus.config.js, package.json, src/components/PluginCardsList/index.tsx, src/components/PluginCardsList/styles.module.css, src/data/plugins.tsx, yarn.lock
Add new Reactjs component to display a list of community plugins generated from a list which is mainted in the file: /src/components/PluginCardsList/index.tsx
This PR does not actually include usage of the component, this will be done in a follow PR (as this change has to be done via a markdown page).
=> feat: add component to display the list of community plugins

docusaurus.config.js
Use the same baseUrl as used in production so that the search links work when using a local dev server to browse the docs.
Resolves https://github.com/thin-edge/tedge-docs/issues/48
**Note**
The search function is still using an index generated from the production logs, so it will not included results for any new pages, so don't be surprised if some 404 links are still occur.
=> fix: support searching when using dev server by using same baseUrl as prod

docusaurus.config.js
Replace the thin-edge.io placeholder text from `{{te}}` to `%%te%%` to avoid a problem with the mdx file checker, https://github.com/slorber/docusaurus-mdx-checker.
The `{{}}` syntax would cause an error when validating the documentation in the thin-edge.io PR checks due to the variable not being defined at the time of the check. The new syntax does not trigger such a false negative.
=> feat: replace thin-edge.io placeholder syntax to avoid false negatives when checking for unused global variables

docusaurus.config.js
Add a frontmatter processor to support replacing `%%te%%` with the product name  (without styling).
This enables the page previews displayed in the `<DocCardList />` to show the substituted variable value instead of the placeholder (though only if the page has set the `description` frontmatter property).
An example page using a frontmatter description:
````
---
title: Build
tags: [Contribute, Build]
description: This page details how to build %%te%% from the source code.
---
This page details how to build %%te%% from the source code.
````
In both cases the `%%te%%` will be replaced with the product name (e.g. currently set to `thin-edge.io`).
=> feat: support thin-edge.io text replacements in frontmatter descriptions

.github/workflows/publish.yml, .github/workflows/snapshot.yml, justfile
Add a github workflow to create thin-edge.io version snapshots. The workflow can be manually triggered, or via the thin-edge.io project (https://github.com/thin-edge/thin-edge.io/pull/2702).
* The version list is automatically generated via jq (based on the version-* folders)
* Trigger thin-edge github pages publish job when merging into main
=> feat: create snapshot workflow

.github/workflows/snapshot.yml
Fix bug where the git push didn't have credentials to push the branch
=> ci: reuse checkout credentials to push branch

.github/workflows/snapshot.yml
Fix an issue where creating a doc snapshot from a branch would still try to reference a tag (due to inverted logic in the tag/branch check)
=> fix(ci): snapshot from branch reference

.github/workflows/publish.yml
Set option to update the Algolia search index when deploying the gh pages (introduced in [thin-edge.io #2927](https://github.com/thin-edge/thin-edge.io/pull/2927).
It should only be mergdd after the above PR is merged.
=> ci: update search index when triggering gh_pages deployment

package.json, src/components/UserContext/index.js, src/components/UserContextForm/index.js, src/css/custom.css, yarn.lock
The goal is to provide components which allow documentation which is more use-focused, and allows the user to provide their context (e.g. Urls, device id etc.) which will then be reflected in the documentation.
The following two React components have been added:
* `<UserContextForm>` - Form to allow users to edit the values used in the docs
* `<UserContext>` - Component which will replace variable references with the user provided values
The user context values are saved in the user's local storage in the Web browser, so the values are persisted across sessions.
The new components are not yet used, however they will be used in a follow up PR in the source documentation.
=> feat: add user context components to allow users to customize the instructions

package.json, src/components/UserContext/index.js, src/components/UserContextForm/index.js, yarn.lock
Fix an issue with the previous `<UserContext*>` components which resulted in the production builds failing.
Switched to using a different library that didn't have the same problem, and also wrapped the `<UserContextForm>` in the `<BrowserOnly>` component to prevent it rendering before the local storage is available (which is provides the persistence layer).
=> fix: switch to usehooks-ts lib to fix build issue caused by accessing local storage during server side rendering

package.json, versioned_docs/version-0.13.1/contribute/INSTALLING_DOCKER.md, versioned_docs/version-0.13.1/references/domain-model.md, versioned_docs/version-0.13.1/start/connect-aws.md, yarn.lock
Upgrade to docusaurus 3.4
The PR also includes two minor broken anchor fixes for version 0.13.1 which were detected by the new docusaurus version.
=> chore: update to docusaurus 3.4

scripts/checkout-version.sh
Replaced `-depth` with `-maxdepth` as it is supported on gnu find, and the former is not.
=> fix: checkout version logic which used an incorrect find argument

scripts/checkout-version.sh
Absence of the `-mindepth 1` argument on the find command resulted in the root folder also being matched.
=> fix: checkout version logic should ignore source folder

docusaurus.config.js, package.json, yarn.lock
Update to [docusaurus 3.6](https://docusaurus.io/blog/releases/3.6).
Enable the faster build process (introduced in 3.6) which uses Rspack to speed up the build times.
=> chore: update to docusaurus 3.6 and enable Rspack for faster builds

src/components/UserContextForm/index.js, src/css/custom.css
Scope the CSS rules which were introduced in https://github.com/thin-edge/tedge-docs/pull/78, which affected the CSS rules for the input box used in the Community Plugins List.
**Before**
See the vertical alignment of the "Search plugins" placeholder on the second input box.
**After**
=> fix: scope user context component css rules to prevent conflicts with plugins input box

README.md, justfile
Use Node.js [corepack](https://nodejs.org/api/corepack.html) to manage the yarn package manager version used in the project.
Include additional small fixes to the README instructions on setting up the project for local development.
=> dev: Use corepack to manage yarn version

src/components/UserContext/index.js
Support passing the title through to the code block.
**Example**
````
<UserContext language="sh" title="Output">
```sh
c8y.url=$C8Y_URL
c8y.profiles.second.url=other.cumulocity.com
```
</UserContext>
````
=> fix(user-context): pass title through to code block

src/data/plugins.tsx
Removing the [meta-tedge-project](https://github.com/thin-edge/meta-tedge-project) in the plugins list as the kas project files have been moved to the [meta-tedge](https://github.com/thin-edge/meta-tedge) repository.
=> docs(plugins): remove meta-tedge-project and extend meta-tedge repo description to mention kas project files

versioned_docs/version-1.5.0/.version, versioned_docs/version-1.5.0/install/index.md, versioned_docs/version-1.5.0/start/getting-started.md
Update the 1.5.0 doc snapshot to include instructions how users can install thin-edge.io if the device is sitting behind a http proxy.
=> docs: backport instructions to install from behind a http proxy
